# Generated by Django 3.1.1 on 2020-09-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('company', '0006_auto_20200906_2226'),
        ('employee', '0002_auto_20200906_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
