# Generated by Django 3.1.1 on 2020-09-07 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=31, null=True)),
                ('cpf', models.CharField(max_length=31)),
                ('telephone', models.CharField(blank=True, max_length=31, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['cpf'], name='person_cpf_idx'),
        ),
    ]
