# Generated by Django 3.1.1 on 2020-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
