# Generated by Django 3.1.1 on 2020-09-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200906_1844'),
        ('company', '0004_auto_20200906_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employee.Employee'),
        ),
    ]
