# Generated by Django 3.1.1 on 2020-09-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0005_auto_20200906_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['cnpj'], name='company_cnpj_idx'),
        ),
    ]
