# Generated by Django 3.1.1 on 2020-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0006_auto_20200906_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
